"use client";
import { use, useEffect,useState } from "react";
import type { CarouselComment } from "@/lib/carousel-gen/types";
type Review={id:string;title:string;aspectRatio:string;slides:{id:string;headline:string}[];caption:string;currentRevisionId:string};
export default function CarouselReview({params}:{params:Promise<{token:string}>}) {
 const {token}=use(params);const [deck,setDeck]=useState<Review|null>(null),[comments,setComments]=useState<CarouselComment[]>([]),[index,setIndex]=useState(0),[name,setName]=useState(''),[content,setContent]=useState(''),[general,setGeneral]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch(`/api/carousels/review?token=${token}`);const data=await r.json();if(!r.ok)throw Error(data.error?.message || 'Review unavailable');setDeck(data.carousel);setComments(data.comments);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[token]);
 async function act(action:string,commentId?:string){if(!deck)return;setBusy(true);setError('');try{const r=await fetch('/api/carousels/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,carouselId:deck.id,revisionId:deck.currentRevisionId,guestName:name || undefined,slideId:general?null:deck.slides[index].id,content:content || undefined,commentId})});const data=await r.json();if(!r.ok)throw Error(data.error?.message || 'Action failed');setStatus(action==='approve'?'This revision is approved.':action==='request_changes'?'Changes requested.':'Feedback saved.');setContent('');await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-zinc-50 p-4 md:p-8 text-zinc-900"><div className="max-w-6xl mx-auto"><h1 className="text-2xl font-semibold">{deck?.title || 'Carousel review'}</h1><p className="mt-2 text-sm">Review a fixed revision. Guest names are self-reported.</p>{error && <p role="alert" className="p-3 bg-red-50 text-red-800">{error}</p>}{status && <p role="status" className="p-3 bg-green-50">{status}</p>}{deck && <div className="grid md:grid-cols-2 gap-8 mt-6"><section><img className="w-full shadow-lg" alt={deck.slides[index]?.headline || `Slide ${index+1}`} src={`/api/carousels/review?token=${token}&slide=${index}`}/><div className="flex justify-between py-4"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Previous</button><span>{index+1} / {deck.slides.length}</span><button disabled={index===deck.slides.length-1} onClick={()=>setIndex(i=>i+1)}>Next</button></div><p className="whitespace-pre-wrap">{deck.caption}</p></section><section className="space-y-4"><label className="block">Your name<input className="block w-full border rounded p-3" value={name} onChange={e=>setName(e.target.value)}/></label><label className="block">Feedback<textarea className="block w-full border rounded p-3" value={content} onChange={e=>setContent(e.target.value)}/></label><label><input type="checkbox" checked={general} onChange={e=>setGeneral(e.target.checked)}/> Comment on the whole deck</label><div className="flex flex-wrap gap-3"><button disabled={busy || !name || !content} className="rounded bg-zinc-900 text-white p-3" onClick={()=>void act('add_comment')}>Add comment</button><button disabled={busy || !name} className="border rounded p-3" onClick={()=>void act('approve')}>Approve this revision</button><button disabled={busy || !name} className="border rounded p-3" onClick={()=>void act('request_changes')}>Request changes</button></div>{comments.filter(c=>c.slideId===null || c.slideId===deck.slides[index].id).map(c=><article className="border bg-white rounded p-4" key={c.id}><p className="font-medium">{c.author.name} · Guest · {c.slideId?'Slide feedback':'General feedback'}</p><p className="whitespace-pre-wrap my-2">{c.content}</p><button disabled={busy} onClick={()=>void act(c.resolved?'reopen_comment':'resolve_comment',c.id)}>{c.resolved?'Reopen':'Resolve'}</button></article>)}</section></div>}</div></main>;
}
